"""Added is_superuser and created_at for user table

Revision ID: 22244927f95c
Revises: 837187ab46f8
Create Date: 2025-05-18 17:04:52.745886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import os
from datetime import datetime, timezone
from zoneinfo import ZoneInfo


# revision identifiers, used by Alembic.
revision: str = '22244927f95c'
down_revision: Union[str, None] = '837187ab46f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column(
        'users', 
        sa.Column(
            'created_at', 
            sa.DateTime(), 
            nullable=False, 
            server_default=sa.text('CURRENT_TIMESTAMP')
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
