"""Remove unique Constraint in tag table for tag name.

Revision ID: 5378acef7f8d
Revises: 73f1c966c531
Create Date: 2025-06-03 02:03:42.281484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5378acef7f8d'
down_revision: Union[str, None] = '73f1c966c531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_name_key', 'tags', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tags_name_key', 'tags', ['name'])
    # ### end Alembic commands ###
