"""Added user.id to control for website table.

Revision ID: 6e2c4632de09
Revises: 22244927f95c
Create Date: 2025-05-18 23:47:53.396315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2c4632de09'
down_revision: Union[str, None] = '22244927f95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('owner_id', sa.Integer(), nullable=True, server_default="1"))
    op.create_foreign_key(
        constraint_name="fk_websites_owner_id",
        source_table="websites",
        referent_table="users",
        local_cols=["owner_id"],
        remote_cols=["id"],
        ondelete="CASCADE"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'websites', type_='foreignkey')
    op.drop_column('websites', 'owner_id')
    # ### end Alembic commands ###
